spring:
  application:
    name: api-gateway
  config:
    import: "optional:nacos:gmall-api-gateway.yml?group=GMALL&refreshEnabled=true"
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/gmall
    username: gmall
    password: gmall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    nacos:
      config:
        enabled: false
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      enabled: false
      transport:
        dashboard: 127.0.0.1:8080
server:
  port: 18070
management:
  endpoints:
    web:
      exposure:
        include: health,info
gmall:
  mall-bff:
    base-url: http://127.0.0.1:18072
  admin-bff:
    base-url: http://127.0.0.1:18071
